modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="questinstaller"
version="1.1.0"
displayName="Minecolonies Quest Installer"
logoFile="logo.png"
authors="hogbits"
description='''
Adds a Minecolonies questline for FTB Quests.
'''

[[dependencies.questinstaller]]
modId="minecolonies"
mandatory=false
versionRange="[1.20.1-1.1.60-BETA,)"
ordering="NONE"
side="BOTH"

[[dependencies.questinstaller]]
modId="ftbquests"
mandatory=false
versionRange="[2001.4.14,)"
ordering="NONE"
side="BOTH"